# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build chocofi nice_nano_v2 mousekeyspr soft_off'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right"]'
      alphas: '["default"]'
      extra: '["default"]'
      tap: '["colemakdhk"]'
      nav: '["default"]'
      clipboard: '["mac"]'
      layers: '["default"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR\n#define MIRYOKU_KLUDGE_SOFT_OFF"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y\CONFIG_ZMK_PM_SOFT_OFF=y"]'
      branches: '["petejohanson/zmk/feat/pointers-move-scroll","zmkfirmware/zmk/main petejohanson/zmk/feat/pointers-move-scroll"]'
